apiVersion: skaffold/v4beta11
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: kushalsomaliya/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
          - "**/*.css"
          - "**/*.html"
    - image: kushalsomaliya/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
    - image: kushalsomaliya/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
manifests:
  rawYaml:
    - k8s/*.yaml
    # - k8s/client-deployment.yaml
    # - k8s/server-deployment.yaml
    # - k8s/worker-deployment.yaml
